services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#    api.repository.chat_repository:
#        class: ApiBundle\Repository\ChatRepository
#        arguments: ['\ApiBundle\Entity\Chat']

    api.service.chat:
        class: ApiBundle\Service\ApiService

#        calls:
#          - [setRepository, 'api.repository.chat_repository']
