services:
#    account.example:
#        class: AccountBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    account.managers.account_manager:
        class: AccountBundle\Managers\AccountManager
        arguments: ['@doctrine.orm.entity_manager']