services:
#    api.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

#    app.manager.chat:
#        class: AppBundle\Managers\ChatManager
#        lazy: true
#        arguments: ['@doctrine.orm.entity_manager']
#
#    app.service.chat_service:
#        class: AppBundle\Service\ChatService
#        arguments:
#          - '@app.manager.chat'
#          - '@knp_paginator'
#
#    app.managers.chat_messages_managers:
#        class: AppBundle\Managers\MessagesManager
#        arguments: ['@doctrine.orm.entity_manager']
#
#    app.service.chat_messages_service:
#        class: AppBundle\Service\MessageService
#        arguments: ['@app.manager.chat']
#
#    app.managers.account_managers:
#        class: AppBundle\Managers\AccountManager
#        arguments: ['@doctrine.orm.entity_manager']

#       calls:
#          - [setRepository, 'api.repository.chat_repository']
